---
  on:
    pull_request:
  
  jobs:
    integration-macos:
      runs-on: macos-latest
      strategy:
        matrix:
          os:
            - macos-latest
          suite:
            - default
        fail-fast: false
      steps:
        - name: Check out code
          uses: actions/checkout@main
        - name: Install Chef
          uses: actionshub/chef-install@main
        - name: Test-Kitchen Converge
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: converge
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.exec.yml
        - name: Test-Kitchen Verify
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: verify
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.exec.yml