on:
  pull_request:

jobs:
  markdownlint:
    uses: snohio/github-workflows/.github/workflows/markdown-lint.yml@main

  yamllint:
    uses: snohio/github-workflows/.github/workflows/yaml-lint.yml@main

  jsonlint:
    uses: snohio/github-workflows/.github/workflows/json-lint.yml@main

  cookstylelint:
    uses: snohio/github-workflows/.github/workflows/cookstyle-lint.yml@main

  kitchen-vagrant:
    runs-on: macos-latest
    strategy:
      matrix:
        os: ['windows-2022', 'almalinux-9']
        suite: ['default']
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Test-Kitchen Create
        uses: actionshub/test-kitchen@main
        with:
          os: ${{ matrix.os }}
          action: create
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.vagrant.yml
          TERM: xterm-256color
      - name: Test-Kitchen Converge
        uses: actionshub/test-kitchen@main
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          action: converge
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.vagrant.yml
          TERM: xterm-256color
      - name: Test-Kitchen Verify
        uses: actionshub/test-kitchen@main
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          action: verify
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.vagrant.yml
